AWSTemplateFormatVersion: "2010-09-09"
Description: Parent template to deploy all AWS Services

Parameters:
  CFBucket:
    Type: String
    Description: "S3 bucket where nested templates are stored"

  CFBucketPrefix:
    Type: String
    Description: "Prefix for template files"

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${CFBucket}/${CFBucketPrefix}/vpc.yaml
      Parameters:
        projectName: myproject
        envName: dev
        vpcCidrBlock: 10.72.0.0/16
        numberOfSubnets: 4
      TimeoutInMinutes: 15

  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${CFBucket}/${CFBucketPrefix}/ecs.yaml
      Parameters:
        projectName: myproject
        envName: dev
        instanceType: t2.micro
        desiredCapacity: 2
        maxSize: 5
        vpcId: !GetAtt VPCStack.Outputs.VpcId
        subnetIds: !Join [",", [!GetAtt VPCStack.Outputs.PrivateSubnet1Id, !GetAtt VPCStack.Outputs.PrivateSubnet2Id]]
      TimeoutInMinutes: 30

  ECSServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ECSStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${CFBucket}/${CFBucketPrefix}/ecs-service.yaml
      Parameters:
        projectName: myproject
        envName: dev
        containerCpu: 256
        containerMemory: 512
        containerPort: 8000
        imageUrl: aashhik/hellopython:v1
        desiredCount: 2
        serviceName: python
        vpcId: !GetAtt VPCStack.Outputs.VpcId
        publicSubnetIds: !Join [",", [!GetAtt VPCStack.Outputs.PublicSubnet1Id, !GetAtt VPCStack.Outputs.PublicSubnet2Id]]
        privateSubnetIds: !Join [",", [!GetAtt VPCStack.Outputs.PrivateSubnet1Id, !GetAtt VPCStack.Outputs.PrivateSubnet2Id]]
        clusterName: !GetAtt ECSStack.Outputs.ClusterName
        ecsTaskExecutionRole: !GetAtt ECSStack.Outputs.ECSTaskExecutionRole
        capacityProvider: !GetAtt ECSStack.Outputs.CapacityProvider