name: Application Build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    name: BUILD IMAGE
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

    # Checkout under Github Workspace
    - name: Check out code
      uses: actions/checkout@v5
    
    # Login to DockerHub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Build Image, Tag and push to DockerHub 
    - name: Build, tag and push image to DockerHub
      run: |
        docker build -f ./app/Dockerfile -t aashhik/hellopython:v1 .
        echo "Pushing image to DockerHub..."
        docker push aashhik/hellopython:v1

  pre-deploy:
    name: CREATE S3 BUCKETS AND AWS ROLES
    needs: ['build']
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_ADMIN_REGION }}

      - name: Create S3 bucket and execution roles for Cloudformation
        run: |
          bash ./prerequisites.sh "${{ vars.BUCKET_NAME }}" "${{ vars.BUCKET_PREFIX }}" "${{ vars.AWS_ADMIN_ACCOUNT_ID }}"