name: Demo Lalals Workflow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  dev_build:
    name: DEV
    if: contains(github.ref_name, 'main')
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      environment: dev